### ISSUE TITLE
Don’t modify original package.json

### ISSUE THREAD

**Issue by niksy** [thlorenz/viralify#2]
It seems like viralify modifies `package.json` for specific package and then leaves it like that after transform is finished. Is it possible to have some sort of "unviralify" function which will return everything to original state?

**Comment by yoshuawuyts** [comment]
Having an `unviralify` command is tricky because you cannot know what packages already have a transform declared in their respective `package.json`. So just flat out removing things won't work. You could ofcourse go down the path of saving the original deps in some external location but that seems very complicated. In the end it's probably easiest to just remove `node_modules` and run `npm install` again.
